name: "Pushpendra - AKS Deployment Pipeline with GitHub Actions"

on:
  push:
  workflow_dispatch:

env:
  TF_LOG: INFO

jobs:
  aks:
    name: "AKS Pipeline"
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Set path to kubeconfig (Windows)
        run: echo "KUBECONFIG=D:/yml/.kube/config" >> $GITHUB_ENV

      - name: K8s Control Apply
        run: kubectl apply -f pyweb.yml
