name: "AKS Deployment Pipeline with GitHub Actions"

on:
  push:
  workflow_dispatch:

env:
  TF_LOG: INFO
  KUBECONFIG: D:\yml\.kube\config

jobs:
  aks:
    name: "AKS Pipeline"
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell
        working-directory: D:\yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Kubernetes access
        id: access
        run: |
          $env:KUBECONFIG="D:\yml\.kube\config"
          kubectl config view

      - name: Verify AKS Connectivity
        run: |
          kubectl get nodes

      - name: K8s Control Apply
        id: apply
        run: |
          kubectl apply -f pyweb.yml
